language: node_js

node_js:
  - "7"

before_script:
  - yarn install
  - yarn build

script: yarn test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master