language: node_js

node_js:
    - 7

cache:
    yarn: true
    directories:
        - node_modules

before_script:
    - yarn install
    - yarn build
#    - echo "starset.studio107.ru" > build/CNAME

script: yarn test

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    fqdn: starset.studio107.ru
    on:
        branch: master